package ch.unil.softarch.luxurycarrental.service;

import ch.unil.softarch.luxurycarrental.domain.entities.CarType;
import jakarta.enterprise.context.ApplicationScoped;
import jakarta.persistence.EntityManager;
import jakarta.persistence.PersistenceContext;
import jakarta.transaction.Transactional;
import jakarta.ws.rs.WebApplicationException;

import java.util.List;
import java.util.UUID;

/**
 * Service class for managing Car Types (categories/models).
 * <p>
 * This class handles CRUD operations for CarType entities using JPA.
 * It ensures data integrity, such as preventing the deletion of a CarType
 * that is currently linked to physical cars.
 * </p>
 */
@ApplicationScoped
public class CarTypeService {

    // Inject the EntityManager to interact with the database
    @PersistenceContext(unitName = "LuxuryCarRentalPU")
    private EntityManager em;

    // -------------------------------------------------------------------------
    // Create
    // -------------------------------------------------------------------------

    /**
     * Adds a new CarType to the system.
     *
     * @param carType The CarType entity to persist.
     * @return The persisted CarType.
     */
    @Transactional
    public CarType addCarType(CarType carType) {
        // The ID will be automatically generated by the @PrePersist callback in the entity
        em.persist(carType);
        return carType;
    }

    // -------------------------------------------------------------------------
    // Read
    // -------------------------------------------------------------------------

    /**
     * Retrieves a specific CarType by its ID.
     *
     * @param id The UUID of the CarType.
     * @return The found CarType entity.
     * @throws WebApplicationException if the CarType is not found (404).
     */
    public CarType getCarType(UUID id) {
        CarType carType = em.find(CarType.class, id);
        if (carType == null) {
            throw new WebApplicationException("CarType not found", 404);
        }
        return carType;
    }

    /**
     * Retrieves all CarTypes available in the system.
     *
     * @return A list of all CarType entities.
     */
    public List<CarType> getAllCarTypes() {
        // Use JP-QL to fetch all records efficiently
        return em.createQuery("SELECT ct FROM CarType ct", CarType.class).getResultList();
    }

    // -------------------------------------------------------------------------
    // Update
    // -------------------------------------------------------------------------

    /**
     * Updates an existing CarType.
     *
     * @param id     The ID of the CarType to update.
     * @param update An object containing the new values.
     * @return The updated CarType entity.
     * @throws WebApplicationException if the CarType is not found (404).
     */
    @Transactional
    public CarType updateCarType(UUID id, CarType update) {
        CarType existing = em.find(CarType.class, id);
        if (existing == null) {
            throw new WebApplicationException("CarType not found", 404);
        }

        // Apply updates if fields are provided (not null/default)
        if (update.getCategory() != null) existing.setCategory(update.getCategory());
        if (update.getBrand() != null) existing.setBrand(update.getBrand());
        if (update.getModel() != null) existing.setModel(update.getModel());
        if (update.getEngine() != null) existing.setEngine(update.getEngine());
        if (update.getPower() > 0) existing.setPower(update.getPower());
        if (update.getMaxSpeed() > 0) existing.setMaxSpeed(update.getMaxSpeed());
        if (update.getAcceleration() > 0) existing.setAcceleration(update.getAcceleration());
        if (update.getWeight() > 0) existing.setWeight(update.getWeight());
        if (update.getDriveType() != null) existing.setDriveType(update.getDriveType());
        if (update.getTransmission() != null) existing.setTransmission(update.getTransmission());
        if (update.getSeats() > 0) existing.setSeats(update.getSeats());
        if (update.getDescription() != null) existing.setDescription(update.getDescription());
        if (update.getFeatures() != null) existing.setFeatures(update.getFeatures());

        // Changes are automatically synced to DB on transaction commit
        return existing;
    }

    // -------------------------------------------------------------------------
    // Delete
    // -------------------------------------------------------------------------

    /**
     * Removes a CarType from the system.
     * <p>
     * This method performs a check to ensure no Cars are currently linked to this type.
     * If linked cars exist, deletion is blocked to maintain referential integrity.
     * </p>
     *
     * @param id The ID of the CarType to delete.
     * @return true if deleted successfully.
     * @throws WebApplicationException if not found (404) or if deletion is blocked (400).
     */
    @Transactional
    public boolean removeCarType(UUID id) {
        CarType existing = em.find(CarType.class, id);
        if (existing == null) {
            throw new WebApplicationException("CarType not found", 404);
        }

        // --- Optimized Dependency Check using JP-QL ---
        // Instead of loading all cars into memory, we ask the database directly:
        // "Count how many cars reference this car type ID"
        Long usageCount = em.createQuery(
                        "SELECT COUNT(c) FROM Car c WHERE c.carType.id = :typeId", Long.class)
                .setParameter("typeId", id)
                .getSingleResult();

        if (usageCount > 0) {
            // Prevent deletion if there are cars using this type
            throw new WebApplicationException(
                    "Cannot delete CarType: there are " + usageCount + " cars still using this type", 400);
        }

        // --- Safe to delete ---
        em.remove(existing);
        return true;
    }
}